// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO-iIxJvS_rVmR6TsOmCbIGC42usT5qm8',
    appId: '1:605907459602:web:91b20ffa6fa757c17e42cb',
    messagingSenderId: '605907459602',
    projectId: 'commctv-f2b45',
    authDomain: 'commctv-f2b45.firebaseapp.com',
    storageBucket: 'commctv-f2b45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO-iIxJvS_rVmR6TsOmCbIGC42usT5qm8',
    appId: '1:605907459602:android:91b20ffa6fa757c17e42cb',
    messagingSenderId: '605907459602',
    projectId: 'commctv-f2b45',
    storageBucket: 'commctv-f2b45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuJ1ihsvVGCbcPRHpwfzoiVHw9M-6nvvg',
    appId: '1:605907459602:ios:0c3bd8a6212d63dd7e42cb',
    messagingSenderId: '605907459602',
    projectId: 'commctv-f2b45',
    storageBucket: 'commctv-f2b45.firebasestorage.app',
    iosBundleId: 'com.example.cctvApp',
  );
}
